### ISSUE TITLE
Failed to resolve: com.github.ybq:AndroidSpinKit:v1.0.0

### ISSUE THREAD

**Issue by BigDipper7** [ybq/AndroidSpinKit#1]
Hey Friends,
I can not use your kit,
Is that gradle dependence right? I really can not find it,
Thanks~

**Comment by ybq** [comment]
亲，我刚测试我这是OK的 你的项目根目录加这个了吗？
allprojects {
        repositories {
            ...
            maven { url "https://jitpack.io" }
        }
    }

**Comment by BigDipper7** [comment]
好吧 没有没有 我先去试试 谢啦~ :smile:

**Comment by BigDipper7** [comment]
谢谢 @ybq 终于可以用了，的确就是缺少这句话，谢谢你的控件

**Comment by Mhlfarhad** [comment]
Showing this problem
Execution failed for task ':app:checkDebugAarMetadata'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not find com.github.ybq:AndroidSpinKit:v1.0.0.
     Searched in the following locations:
       - https://maven.google.com/com/github/ybq/AndroidSpinKit/v1.0.0/AndroidSpinKit-v1.0.0.pom
       - https://jitpack.io/com/github/ybq/AndroidSpinKit/v1.0.0/AndroidSpinKit-v1.0.0.pom
       - http://dl.bintray.com/jlmd/maven/com/github/ybq/AndroidSpinKit/v1.0.0/AndroidSpinKit-v1.0.0.pom
       - https://jcenter.bintray.com/com/github/ybq/AndroidSpinKit/v1.0.0/AndroidSpinKit-v1.0.0.pom
       - https://dl.google.com/dl/android/maven2/com/github/ybq/AndroidSpinKit/v1.0.0/AndroidSpinKit-v1.0.0.pom
       - https://cardinalcommerce.bintray.com/android/com/github/ybq/AndroidSpinKit/v1.0.0/AndroidSpinKit-v1.0.0.pom
       - https://dl.bintray.com/payhere/payhere-android-payment/com/github/ybq/AndroidSpinKit/v1.0.0/AndroidSpinKit-v1.0.0.pom
       - https://repo.maven.apache.org/maven2/com/github/ybq/AndroidSpinKit/v1.0.0/AndroidSpinKit-v1.0.0.pom
     Required by:
         project :app

Possible solution:
 - Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html
